### ISSUE TITLE
Segfault when running examples/contractdetails.py

### ISSUE THREAD

**Issue by azyr** [Komnomnomnom/swigibpy#27] opened 2014-08-17 18:08 UTC
Getting segfault when running examples/contractdetails.py. The violating code is starting from line 66:

```python
if contractDetails.secIdList is not None:
    for secId in contractDetails.secIdList:
        print("secIdList: %s" % secId)
else:
    print("secIdList: None")
```

Don't know why is it giving segfault though... Tested with Python 2.7.8, 3.3.4, 3.3.5 and 3.4.1.

**Comment by Komnomnomnom** [comment] 2015-01-12 15:38
@azyr it's been a while but I'm unable to reproduce this, tried on Python 2.7.9, 3.3.5 and on a debug build of Python 2.7.6 with the valgrind memory checker and nothing showed up.

Could you check out the latest version of master, try it again and report back?

**Comment by Komnomnomnom** [comment] 2015-03-16 17:59
Closing as unable to reproduce and no feedback provided

**Closed by Komnomnomnom** 2015-03-16 17:59 UTC
Labels: Bug, SWIG
